version: '3'
services:
  recommender:
    container_name: recommender-container
    hostname: recommender
    build: .
    entrypoint: python botify/server.py
    ports:
      - '5000:5000'
    expose:
      - 5000
    depends_on:
      - redis
    networks:
      - workspace
  redis:
    hostname: redis
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      - workspace

networks:
  workspace:
    external: true